### ISSUE TITLE
janus videoroom doesn't dispay the stream forward by the aiortc  when i run janus example code in aiortc 

### ISSUE THREAD

**Issue by zhiweny1122** [aiortc/aiortc#491] opened 2021-03-03 07:20 UTC
janus videoroom doesn't dispay the stream forward by the aiortc  when i run janus example code in aiortc .
I can the videos when I use chrome ,but i can't see the video from aiortc client .
Is this a bug ?  the log seems ok, but thers is no video in janus default room 1234
my command is as folllow：
python janus.py http://www.streamocean.com:8088/janus

the log is this:
^Croot@wangzhiwen-Vostro-3668:/home/wangzhiwen/aiortc/examples/janus# python janus.py http://www.streamocean.com:8088/janus
id: 2125790959691456, display: bbbb
Exchanging media

**Comment by zhiweny1122** [comment] 2021-03-03 09:11
DEBUG:aiortc.rtcrtpsender:RTCRtpSender(video) > RtpPacket(seq=41177, ts=1975300926, marker=1, payload=97, 100 bytes)
INFO:aioice.ice:Connection(0) Consent to send expired
DEBUG:aioice.ice:Connection(0) protocol(0) connection_lost(None)
DEBUG:aiortc.rtcdtlstransport:RTCDtlsTransport(server) - State.CONNECTED -> State.CLOSED
DEBUG:aiortc.rtcicetransport:RTCIceTransport(controlling) - completed -> failed
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceConnectionState completed -> failed
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() connectionState connected -> failed
DEBUG:aiortc.rtcrtpsender:RTCRtpSender(video) > RtpPacket(seq=41178, ts=1975303926, marker=1, payload=97, 100 bytes)
DEBUG:aiortc.rtcrtpsender:RTCRtpSender(video) - RTP finished

**Comment by jlaine** [comment] 2021-03-03 17:36
I am unable to connect to the Janus server you mentioned so I don't see what you expect here?

**Comment by jlaine** [comment] 2021-03-03 17:43
Also I just checked against the public meetecho server and it works fine.

**Comment by zhiweny1122** [comment] 2021-03-04 01:17
My janus server is set up by myself and it works fine with chrome.
The problem is the aiortc is send data while the dtls is not ok in Janus side.
Is it possible the dtls handshake is not finished and aiortc client begin to send av data ?

aiortc log
DEBUG:aiortc.rtcrtpsender:RTCRtpSender(video) > RtcpSdesPacket(chunks=[RtcpSourceInfo(ssrc=442444978, items=[(1, b'626af073-d531-45aa-9e3b-be63a82ff57c')])])
DEBUG:aiortc.rtcrtpsender:RTCRtpSender(video) > RtcpSrPacket(ssrc=442444978, sender_info=RtcpSenderInfo(ntp_timestamp=16422884526319585816, rtp_timestamp=1975300926, packet_count=1491, octet_count=146266), reports=[])
DEBUG:aiortc.rtcrtpsender:RTCRtpSender(video) > RtcpSdesPacket(chunks=[RtcpSourceInfo(ssrc=442444978, items=[(1, b'626af073-d531-45aa-9e3b-be63a82ff57c')])])
DEBUG:aiortc.rtcrtpsender:RTCRtpSender(video) > RtcpSrPacket(ssrc=442444978, sender_info=RtcpSenderInfo(ntp_timestamp=16422884526319585816, rtp_timestamp=1975300926, packet_count=1491, octet_count=146266), reports=[])
DEBUG:aiortc.rtcrtpsender:RTCRtpSender(video) > RtcpSdesPacket(chunks=[RtcpSourceInfo(ssrc=442444978, items=[(1, b'626af073-d531-45aa-9e3b-be63a82ff57c')])])
DEBUG:aiortc.rtcrtpsender:RTCRtpSender(video) > RtcpSrPacket(ssrc=442444978, sender_info=RtcpSenderInfo(ntp_timestamp=16422884526319585816, rtp_timestamp=1975300926, packet_count=1491, octet_count=146266), reports=[])
DEBUG:aiortc.rtcrtpsender:RTCRtpSender(video) > RtcpSdesPacket(chunks=[RtcpSourceInfo(ssrc=442444978, items=[(1, b'626af073-d531-45aa-9e3b-be63a82ff57c')])])
DEBUG:aiortc.rtcrtpsender:RTCRtpSender(video) > RtcpSrPacket(ssrc=442444978, sender_info=RtcpSenderInfo(ntp_timestamp=16422884526319585816, rtp_timestamp=1975300926, packet_count=1491, octet_count=146266), reports=[])
DEBUG:aiortc.rtcrtpsender:RTCRtpSender(video) > RtcpSdesPacket(chunks=[RtcpSourceInfo(ssrc=442444978, items=[(1, b'626af073-d531-45aa-9e3b-be63a82ff57c')])])
^CDEBUG:aiortc.rtcrtpsender:RTCRtpSender(video) > RtcpByePacket(sources=[442444978])
DEBUG:aiortc.rtcrtpsender:RTCRtpSender(video) - RTCP finished
DEBUG:aiortc.rtcicetransport:RTCIceTransport(controlling) - failed -> closed
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceConnectionState failed -> closed
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() connectionState failed -> closed


Janus side log is as follow:

WARN] [6375562738798611]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [6375562738798611]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [6375562738798611]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [6375562738798611]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [6375562738798611]     Missing valid SRTP session (packet arrived too early?), skipping...
[ERR] [dtls.c:janus_dtls_retry:1118] [6375562738798611] DTLS taking too much time for component 1 in stream 1...
[janus.plugin.videoroom-0x7f71c4009260] No WebRTC media anymore; 0x7f71ec001ab0 0x7f71ec002480
[6375562738798611] WebRTC resources freed; 0x7f71ec001ab0 0x7f71ec001320

**Comment by zhiweny1122** [comment] 2021-03-04 02:31
Can you tell me how to connect meetecho server using aiortc client ?
 python janus.py  http://www.meetecho.com:8088/janus --verbose  ?  it is no dislpay

**Comment by jlaine** [comment] 2021-03-04 06:05
`python janus.py https://janus.conf.meetecho.com/janus`

Your trace looks like a duplicate of #450

**Comment by zhiweny1122** [comment] 2021-03-04 09:12
Hi jlaine:
you are right . 
The aiortc works well when I connect public meetecho server.
I will double check my janus server.
Thanks a lot.

**Comment by jlaine** [comment] 2021-03-04 21:50
OK, could you please report back once you find out what's going on? Thanks!

**Comment by zhiweny1122** [comment] 2021-03-23 07:59
the log from janus side looks like the ssl_read return -1 .
int read = SSL_read(dtls->ssl, &data, 1500);
Is it helpful ?

**Comment by zhiweny1122** [comment] 2021-03-30 05:37
The wireshark show the Janus server send a Tlsv1.2 big packet including the CA certificate to aiortc client and its size is 3165 large than mtu 1500.

![20210330114446](https://user-images.githubusercontent.com/26403439/112938709-b2efa280-915c-11eb-8935-ffe445be4c48.jpg)

**Comment by zhiweny1122** [comment] 2021-03-31 06:03
the public janus server side send the fragment of certificate and reassemble them.
I attached the picture here.
![good20210331135345](https://user-images.githubusercontent.com/26403439/113097672-ec421400-9229-11eb-922c-a1736118aadb.jpg)

**Comment by zhiweny1122** [comment] 2021-03-31 07:52
This issue is resloved when i update the certificate to janus signed.
It is a bug of janus.

**Comment by jlaine** [comment] 2021-03-31 15:42
OK thanks for reporting back, this was also what I suspected.

**Closed by jlaine** 2021-03-31 15:42 UTC
Labels: invalid
