### ISSUE TITLE
Problems with running videostream-cli example

### ISSUE THREAD

**Issue by RyanLiu91** [aiortc/aiortc#477] opened 2021-02-21 23:42 UTC
Getting error: BlockingIOError: [Errno 35] write could not complete without blocking

Full stack trace:
python cli.py offer --verbose
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceGatheringState new -> gathering
DEBUG:aioice.ice:Connection(0) protocol(0) connection_made(<_SelectorDatagramTransport fd=8 read=idle write=<idle, bufsize=0>>)
DEBUG:aioice.ice:Connection(0) protocol(0) > ('74.125.197.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xee{(Z\xd7\x98\x87\xab=v\xe1\xcd')
DEBUG:aioice.ice:Connection(0) protocol(0) < ('74.125.197.127', 19302) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\xee{(Z\xd7\x98\x87\xab=v\xe1\xcd')
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceGatheringState gathering -> complete
-- Please send this message to the remote party --
{"sdp": "v=0\r\no=- 3822939633 3822939633 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic:WMS *\r\nm=video 61288 UDP/TLS/RTP/SAVPF 97 98 99 100 101 102\r\nc=IN IP4 192.168.86.247\r\na=sendrecv\r\na=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=mid:0\r\na=msid:7de90711-c9e2-40fa-a4f7-270fdb239348 12e247ec-b7d4-4f7b-8dc7-dd4a80cf35bd\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtcp-mux\r\na=ssrc-group:FID 132770976 1258785128\r\na=ssrc:132770976 cname:88f44e71-0384-4384-8433-b39100916778\r\na=ssrc:1258785128 cname:88f44e71-0384-4384-8433-b39100916778\r\na=rtpmap:97 VP8/90000\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=rtcp-fb:97 goog-remb\r\na=rtpmap:98 rtx/90000\r\na=fmtp:98 apt=97\r\na=rtpmap:99 H264/90000\r\na=rtcp-fb:99 nack\r\na=rtcp-fb:99 nack pli\r\na=rtcp-fb:99 goog-remb\r\na=fmtp:99 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42001f\r\na=rtpmap:100 rtx/90000\r\na=fmtp:100 apt=99\r\na=rtpmap:101 H264/90000\r\na=rtcp-fb:101 nack\r\na=rtcp-fb:101 nack pli\r\na=rtcp-fb:101 goog-remb\r\na=fmtp:101 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42e01f\r\na=rtpmap:102 rtx/90000\r\na=fmtp:102 apt=101\r\na=candidate:3263c151f33529b954f2c0d9001baef9 1 udp 2130706431 192.168.86.247 61288 typ host\r\na=candidate:6db2e1afe827ed827fa7c23e3ac52427 1 udp 1694498815 67.180.9.221 61288 typ srflx raddr 192.168.86.247 rport 61288\r\na=end-of-candidates\r\na=ice-ufrag:qZo5\r\na=ice-pwd:RYm3JiEpYJWeCZsvYa6sI2\r\na=fingerprint:sha-256 22:AB:DE:3F:98:51:EF:0C:0E:E1:E6:DC:55:92:6D:92:2B:02:D5:AF:02:17:67:95:09:EE:CE:9B:AA:FA:79:9B\r\na=setup:actpass\r\n", "type": "offer"}
-- Please send this message to the remote party --
{"type": "bye"}

DEBUG:aiortc.rtcicetransport:RTCIceTransport(controlling) - new -> closed
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceConnectionState new -> closed
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() connectionState new -> closed
DEBUG:aioice.ice:Connection(0) protocol(0) connection_lost(None)
Traceback (most recent call last):
  File "cli.py", line 161, in <module>
    role=args.role,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "cli.py", line 102, in run
    await signaling.send(pc.localDescription)
  File "/Users/python-project/lib/python3.6/site-packages/aiortc/contrib/signaling.py", line 147, in send
    self._write_pipe.write(object_to_string(descr) + "\n")
BlockingIOError: [Errno 35] write could not complete without blocking

Please take a look, thank you!

**Comment by jlaine** [comment] 2021-02-22 12:26
I believe this is a limitation of the OS X terminal. Try using a different signaling method

**Comment by jlaine** [comment] 2021-02-22 12:32
This looks like a duplicate of #111

**Closed by jlaine** 2021-02-22 12:32 UTC

**Comment by vincedupuis** [comment] 2022-02-22 20:04
Can you explain how to use a different signaling method
