### ISSUE TITLE
example videostream-cli is Failing

### ISSUE THREAD

**Issue by Nishanth009** [aiortc/aiortc#196] opened 2019-07-18 13:36 UTC
Hi,
I ran videostream-cli example as per instructions provided in the readme file. The transmitted video from one peer reached the other(both python peers are in same machine). But after some time transmission stops and when i opened recorded video file, it was corrupted.
I also noticed this "using avstream.codec to pass codec parameters to muxers is deprecated" getting printed at terminal 
What would be the issue?Any thoughts?
Thanks in advance..

**Comment by jlaine** [comment] 2019-07-18 15:09
I really have nothing to go on here, no logs or any steps to reproduce..

The warning from ffmpeg is not the cause of your problem, this is just PyAV using some deprecated ffmpeg APIs.

**Comment by Nishanth009** [comment] 2019-07-22 09:39
There is no error which is getting printed. I could see the frames received by aiortc some of them are corrupted(first few frames are proper).I have attached samples of few received frames.What would be the reason for this.So i have added STUN server in peer connection, didn't solved the problem.I am using 4G network.
```
Also i have run cli.py example(videostream-cli) in different networks and it didn't work.The video frames are not received after offer and answer exchange
```
Reproducing these errors would be easy i guess since i used same example codes. I am attaching the links of samples videos i have tested 

https://sample-videos.com/video123/mp4/360/big_buck_bunny_360p_30mb.mp4

Any thoughts on these issues. Thanks in advance.


![video-178](https://user-images.githubusercontent.com/20472518/61621848-518de580-ac91-11e9-912e-79fb17e20d72.png)
![video-181](https://user-images.githubusercontent.com/20472518/61621849-52267c00-ac91-11e9-9c7d-c3c835f16b4d.png)
![video-182](https://user-images.githubusercontent.com/20472518/61621851-52267c00-ac91-11e9-9b33-4d878ab232b7.png)
![video-218](https://user-images.githubusercontent.com/20472518/61621853-52267c00-ac91-11e9-9bc4-8162964d56dc.png)
![video-232](https://user-images.githubusercontent.com/20472518/61621855-52bf1280-ac91-11e9-8a45-3dfef22aead2.png)

**Comment by jlaine** [comment] 2019-08-17 06:14
I'm still in the dark here, could you at the very least run the example in verbose mode (`-v`) and see if there are any interesting messages?

**Comment by Glunky** [comment] 2019-10-01 13:22
Hi! 
I have a similar problem. I write `python apprtc.py --play-from /dev/video0` on offer side to capture my webcam stream. And on the answer side i write `python cli.py answer --record-to frame-%3d.png`. At first it`s ok, but over time frames become blurry like bellow.
![video-362](https://user-images.githubusercontent.com/42372955/65964905-70191580-e466-11e9-87f8-c21ca370d9af.png)
Also i got 2 problems: 

> Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.

> Application provided invalid, non monotonically increasing dts to muxer in stream 0: 2952 >= 2952

Second log repetaed with 2955, 2858, 2961 and so on.

Is it because wrong reading of webcam stream? If yes how can read webcam stream correctly?
Or what it can be generally?

**Comment by AnasMK** [comment] 2020-01-21 04:39
I have the same problem, did you find any solution?

**Comment by jlaine** [comment] 2020-02-23 10:19
Unless there is some more information from the submitter I'm going to have to close this issue, I have no way to reproduce the issue.

**Comment by jlaine** [comment] 2020-05-17 21:32
AFAICT the video is a symptom of #58, aiortc doesn't currently trigger a Picture Loss Indication

**Closed by jlaine** 2020-05-17 21:32 UTC
Labels: invalid
