### ISSUE TITLE
MediaRecorder: unnecessary transcoding?

### ISSUE THREAD

**Issue by mqgmaster** [aiortc/aiortc#422] opened 2020-10-10 00:31 UTC
The solution proposed by @jlaine at issue #167 works great (thanks) but the stream is suffering an unnecessary transcoding process by MediaRecorder. 

Why?  

FFmpeg bypass the transcoding by using the flag "-c copy", but the option is ignored by MediaRecorder (or pyAV).

Any idea for help on this?

```
WARNING:av.container.output:Some options were not used: {'c': 'copy'}
```

**Comment by jlaine** [comment] 2020-10-15 06:39
Duplicate of #420

**Closed by jlaine** 2020-10-15 06:39 UTC
