### ISSUE TITLE
Cannot install `aiortc` on M1 MacOS

### ISSUE THREAD

**Issue by roman-verbit-ai** [aiortc/aiortc#633] opened 2022-01-27 13:32 UTC
Still experiencing problems with installing `aiortc` on the new M1 Macs.
There's a related issue here: https://github.com/aiortc/aiortc/issues/241
But it is closed, so opening a new one, so this gets proper attention.

This is the compilation error I get when trying to `pip install aiortc`:
```
>> pip3 install aiortc
Collecting aiortc
  Using cached aiortc-1.2.1.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: aioice<0.8.0,>=0.7.5 in ./venv/lib/python3.8/site-packages (from aiortc) (0.7.5)
Requirement already satisfied: av<9.0.0,>=8.0.0 in ./venv/lib/python3.8/site-packages (from aiortc) (8.1.0)
Requirement already satisfied: cffi>=1.0.0 in ./venv/lib/python3.8/site-packages (from aiortc) (1.15.0)
Requirement already satisfied: cryptography>=2.2 in ./venv/lib/python3.8/site-packages (from aiortc) (36.0.1)
Requirement already satisfied: google-crc32c>=1.1 in ./venv/lib/python3.8/site-packages (from aiortc) (1.3.0)
Requirement already satisfied: pyee>=6.0.0 in ./venv/lib/python3.8/site-packages (from aiortc) (9.0.3)
Requirement already satisfied: pylibsrtp>=0.5.6 in ./venv/lib/python3.8/site-packages (from aiortc) (0.7.0)
Requirement already satisfied: dnspython in ./venv/lib/python3.8/site-packages (from aioice<0.8.0,>=0.7.5->aiortc) (2.2.0)
Requirement already satisfied: netifaces in ./venv/lib/python3.8/site-packages (from aioice<0.8.0,>=0.7.5->aiortc) (0.10.6)
Requirement already satisfied: pycparser in ./venv/lib/python3.8/site-packages (from cffi>=1.0.0->aiortc) (2.21)
Requirement already satisfied: typing-extensions in ./venv/lib/python3.8/site-packages (from pyee>=6.0.0->aiortc) (4.0.1)
Building wheels for collected packages: aiortc
  Building wheel for aiortc (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/himmelroman/aiortc_test/venv/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0f/n3tvjhkj7mbdxs7_1px1m4200000gn/T/pip-install-_cd41arq/aiortc_70eb24234f234a82a7aac57a3ed5def0/setup.py'"'"'; __file__='"'"'/private/var/folders/0f/n3tvjhkj7mbdxs7_1px1m4200000gn/T/pip-install-_cd41arq/aiortc_70eb24234f234a82a7aac57a3ed5def0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/0f/n3tvjhkj7mbdxs7_1px1m4200000gn/T/pip-wheel-51oceksu
       cwd: /private/var/folders/0f/n3tvjhkj7mbdxs7_1px1m4200000gn/T/pip-install-_cd41arq/aiortc_70eb24234f234a82a7aac57a3ed5def0/
  Complete output (50 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14-arm64-3.8
  creating build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/rtcsctptransport.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/rtcconfiguration.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/rtcrtpparameters.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/rtcdtlstransport.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/rtcdatachannel.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/mediastreams.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/jitterbuffer.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/rtcrtpsender.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/events.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/rate.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/clock.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/rtcpeerconnection.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/__init__.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/about.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/rtcicetransport.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/rtcrtpreceiver.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/utils.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/stats.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/exceptions.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/sdp.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/rtcsessiondescription.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/rtp.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  copying src/aiortc/rtcrtptransceiver.py -> build/lib.macosx-10.14-arm64-3.8/aiortc
  creating build/lib.macosx-10.14-arm64-3.8/aiortc/codecs
  copying src/aiortc/codecs/h264.py -> build/lib.macosx-10.14-arm64-3.8/aiortc/codecs
  copying src/aiortc/codecs/g711.py -> build/lib.macosx-10.14-arm64-3.8/aiortc/codecs
  copying src/aiortc/codecs/__init__.py -> build/lib.macosx-10.14-arm64-3.8/aiortc/codecs
  copying src/aiortc/codecs/opus.py -> build/lib.macosx-10.14-arm64-3.8/aiortc/codecs
  copying src/aiortc/codecs/vpx.py -> build/lib.macosx-10.14-arm64-3.8/aiortc/codecs
  copying src/aiortc/codecs/base.py -> build/lib.macosx-10.14-arm64-3.8/aiortc/codecs
  creating build/lib.macosx-10.14-arm64-3.8/aiortc/contrib
  copying src/aiortc/contrib/media.py -> build/lib.macosx-10.14-arm64-3.8/aiortc/contrib
  copying src/aiortc/contrib/signaling.py -> build/lib.macosx-10.14-arm64-3.8/aiortc/contrib
  copying src/aiortc/contrib/__init__.py -> build/lib.macosx-10.14-arm64-3.8/aiortc/contrib
  running build_ext
  creating build/temp.macosx-10.14-arm64-3.8
  creating build/temp.macosx-10.14-arm64-3.8/build
  creating build/temp.macosx-10.14-arm64-3.8/build/temp.macosx-10.14-arm64-3.8
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/Users/himmelroman/aiortc_test/venv/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c build/temp.macosx-10.14-arm64-3.8/aiortc.codecs._opus.c -o build/temp.macosx-10.14-arm64-3.8/build/temp.macosx-10.14-arm64-3.8/aiortc.codecs._opus.o
  build/temp.macosx-10.14-arm64-3.8/aiortc.codecs._opus.c:570:10: fatal error: 'opus/opus.h' file not found
  #include <opus/opus.h>
           ^~~~~~~~~~~~~
  1 error generated.
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for aiortc
  Running setup.py clean for aiortc
Failed to build aiortc
Installing collected packages: aiortc
    Running setup.py install for aiortc ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/himmelroman/aiortc_test/venv/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0f/n3tvjhkj7mbdxs7_1px1m4200000gn/T/pip-install-_cd41arq/aiortc_70eb24234f234a82a7aac57a3ed5def0/setup.py'"'"'; __file__='"'"'/private/var/folders/0f/n3tvjhkj7mbdxs7_1px1m4200000gn/T/pip-install-_cd41arq/aiortc_70eb24234f234a82a7aac57a3ed5def0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/0f/n3tvjhkj7mbdxs7_1px1m4200000gn/T/pip-record-4f_1ytdp/install-record.txt --single-version-externally-managed --compile --install-headers /Users/himmelroman/aiortc_test/venv/include/site/python3.8/aiortc
         cwd: /private/var/folders/0f/n3tvjhkj7mbdxs7_1px1m4200000gn/T/pip-install-_cd41arq/aiortc_70eb24234f234a82a7aac57a3ed5def0/
    Complete output (52 lines):
    running install
    ...
    ...
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/himmelroman/aiortc_test/venv/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0f/n3tvjhkj7mbdxs7_1px1m4200000gn/T/pip-install-_cd41arq/aiortc_70eb24234f234a82a7aac57a3ed5def0/setup.py'"'"'; __file__='"'"'/private/var/folders/0f/n3tvjhkj7mbdxs7_1px1m4200000gn/T/pip-install-_cd41arq/aiortc_70eb24234f234a82a7aac57a3ed5def0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/0f/n3tvjhkj7mbdxs7_1px1m4200000gn/T/pip-record-4f_1ytdp/install-record.txt --single-version-externally-managed --compile --install-headers /Users/himmelroman/aiortc_test/venv/include/site/python3.8/aiortc Check the logs for full command output.
```

After some attempts, I found the packages installed in brew Cellar and worked out how to point `pip` to the correct `include` and `lib` directories.
The package compiles and installs successfully when running this:
```
pip3 install \ 
   --global-option=build_ext 
   --global-option="-I/opt/homebrew/Cellar/opus/1.3.1/include:/opt/homebrew/Cellar/libvpx/1.11.0/include" \
   --global-option="-L/opt/homebrew/Cellar/opus/1.3.1/lib:/opt/homebrew/Cellar/libvpx/1.11.0/lib" aiortc
```
This is only pointing pip to the lib and include paths.
But there is still some mismatch during runtime, when trying to do actually import objects from `aiortc`.
This is the output I get:
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/himmelroman/aiortc_test/WebRTCPeer.py", line 3, in <module>
    from aiortc import RTCPeerConnection, RTCConfiguration, MediaStreamTrack
  File "/Users/himmelroman/aiortc_test/venv/lib/python3.8/site-packages/aiortc/__init__.py", line 11, in <module>
    from .rtcdtlstransport import (
  File "/Users/himmelroman/aiortc_test/venv/lib/python3.8/site-packages/aiortc/rtcdtlstransport.py", line 12, in <module>
    import pylibsrtp
  File "/Users/himmelroman/aiortc_test/venv/lib/python3.8/site-packages/pylibsrtp/__init__.py", line 4, in <module>
    from ._binding import ffi, lib
ImportError: dlopen(/Users/himmelroman/aiortc_test/venv/lib/python3.8/site-packages/pylibsrtp/_binding.abi3.so, 0x0002): symbol not found in flat namespace '_srtp_add_stream'
```
I'm not an expert on linkage, but it looks like the the code was compiled against a version which is different to the one it's linking to. Judging by the words "symbol not found".
This could be introduced by me, due to the include/lib paths I fed to pip when installing.
But I'm not sure how to investigate which libs python is really loading in runtime and compare that to what the paths I provided.

Help would be appreciated!

**Comment by jlaine** [comment] 2022-01-31 20:49
Duplicate of #579

**Closed by jlaine** 2022-01-31 20:49 UTC
