### ISSUE TITLE
How can i integrate aiortc in django?

### ISSUE THREAD

**Issue by faizankarim** [aiortc/aiortc#142] opened 2019-02-08 08:21 UTC
Need help i want to integrate aiortc in django.. Is it possible? Like i want to use same server example with django app...

**Comment by jlaine** [comment] 2019-02-08 15:17
This is a duplicate of #56

**Comment by jlaine** [comment] 2019-02-08 15:20
"Integration with Django" isn't very descriptive, it entirely depends on what you want to do. One note though: Django is not natively designed to work with asyncio, so I'm not convinced you'll want them to live in the same process.

**Closed by jlaine** 2019-02-08 15:20 UTC
Labels: question

**Comment by faizankarim** [comment] 2019-02-11 09:58
ok, so i am trying to attach front end in another application and backend in another application can i do that??? something like api i can call from django or any other we framework???

**Comment by faizankarim** [comment] 2019-02-11 10:34
done there was error of cors , aiohttp_cors lib helped me.

**Comment by ghosthapper** [comment] 2021-03-24 05:50
Hi, I am working on the Django project actually I got structed while integrating aiortc server into a Django project. 
Is it possible to integrate with Django? So, can u suggest any ideas regrading to this.
