### ISSUE TITLE
Laggy/Missing audio frames in server example when we change file reading to user audio track

### ISSUE THREAD

**Issue by mmoallemi99** [aiortc/aiortc#509] opened 2021-03-15 15:31 UTC
Hi Dear maintainers,

I hope you are loud and proud <3

I have this issue with audio tracks in which some of the audio frames/packets are missing and not sent to the user or encoder.

Consider the following steps to reproduce the issue:
1. Open `server` example of the repository, [server example](https://github.com/aiortc/aiortc/tree/main/examples/server)
2. Modify [line 142 of sever.py](https://github.com/aiortc/aiortc/blob/01ff209cc38e887edeb05cba1845cf458b31a0ac/examples/server/server.py#L142), so it returns user's audio track to them. `pc.addTrack(player.audio)` => `pc.addTrack(track)`
3. Start the server and test the audio-only connection
4. Try talking and you will see the audio lag

I've been trying to encode the audio/video and some audio samples are missing, which will cause bad PTS values for FFmpeg and make the audio play faster, once you try to fix the PTS to sync the video you'll see the live audio lag again.

Thanks for your time and kindness.

**Comment by jlaine** [comment] 2021-03-15 17:06
So basically this is a duplicate of #496 ?

**Comment by mmoallemi99** [comment] 2021-03-15 17:52
Exactly, 100% the same issue, sorry I couldn't find out it's duplicate.

**Closed** 2021-03-15 19:09 UTC
