### ISSUE TITLE
webcam example silently fails with firefox without STUN servers

### ISSUE THREAD

**Issue by RemiCardona** [aiortc/aiortc#537] opened 2021-06-08 14:11 UTC
Hi all,

I'm trying to get the webcam example running locally and it's been a partial success. Clicking the "start" button from Firefox (89) with the page loaded as either http://localhost:8080/ or http://127.0.0.1:8080/ doesn't display anything. I do see my webcam light turn on but that's about it.

Std output is as follow
```
test_aiortc38 ~/Projects/test_aiortc $ python webcam.py --host=127.0.0.1 --verbose
DEBUG:asyncio:Using selector: EpollSelector
======== Running on http://127.0.0.1:8080 ========
(Press CTRL+C to quit)
INFO:aiohttp.access:127.0.0.1 [07/Jun/2021:20:48:25 +0000] "GET / HTTP/1.1" 200 985 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
INFO:aiohttp.access:127.0.0.1 [07/Jun/2021:20:48:25 +0000] "GET /client.js HTTP/1.1" 200 2437 "http://127.0.0.1:8080/" "Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
INFO:aiohttp.access:127.0.0.1 [07/Jun/2021:20:48:29 +0000] "GET / HTTP/1.1" 200 985 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
INFO:aiohttp.access:127.0.0.1 [07/Jun/2021:20:48:29 +0000] "GET /client.js HTTP/1.1" 200 2437 "http://127.0.0.1:8080/" "Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
INFO:aiohttp.access:127.0.0.1 [07/Jun/2021:20:48:29 +0000] "GET /favicon.ico HTTP/1.1" 404 178 "http://127.0.0.1:8080/" "Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
DEBUG:aiortc.contrib.media:MediaRelay(140410939534640) Create proxy 140410937716944 for source 140410939535120
DEBUG:aiortc.rtcicetransport:RTCIceTransport(controlled) - new -> closed
INFO:aioice.ice:Connection(0) Remote candidate "60184344-3dea-40b3-aac7-d2a4fd34b0f8.local" could not be resolved
INFO:aioice.ice:Connection(0) Remote candidate "73c8be97-112c-4af7-8893-024b60d223d4.local" could not be resolved
INFO:aioice.ice:Connection(0) Remote candidate "60184344-3dea-40b3-aac7-d2a4fd34b0f8.local" could not be resolved
INFO:aioice.ice:Connection(0) Remote candidate "73c8be97-112c-4af7-8893-024b60d223d4.local" could not be resolved
INFO:aioice.ice:Connection(0) Remote candidate "60184344-3dea-40b3-aac7-d2a4fd34b0f8.local" could not be resolved
INFO:aioice.ice:Connection(0) Remote candidate "73c8be97-112c-4af7-8893-024b60d223d4.local" could not be resolved
INFO:aioice.ice:Connection(0) Remote candidate "60184344-3dea-40b3-aac7-d2a4fd34b0f8.local" could not be resolved
INFO:aioice.ice:Connection(0) Remote candidate "73c8be97-112c-4af7-8893-024b60d223d4.local" could not be resolved
INFO:aioice.ice:Connection(0) Components {1} have no candidate pairs
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceGatheringState new -> gathering
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceGatheringState gathering -> complete
INFO:aiohttp.access:127.0.0.1 [07/Jun/2021:20:48:31 +0000] "POST /offer HTTP/1.1" 200 2036 "http://127.0.0.1:8080/" "Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
^CDEBUG:aiortc.rtcicetransport:RTCIceTransport(controlled) - new -> closed
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceConnectionState new -> closed
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() connectionState new -> closed
Connection state is closed
```

Inside Firefox's console, there's nothing to be seen. No error or warning or anything, just… nothing.

Thinking I might be hitting #524, I modified `webcam.py` like so, to no avail :
```diff
-pc = RTCPeerConnection()
+pc = RTCPeerConnection(configuration=RTCConfiguration(iceServers=[]))
```

I did try setting Firefox's `media.peerconnection.ice.loopback` to `true`, that didn't help either.

Things to note:
- enabling STUN servers (on the client side), does allow the whole thing to run and the video plays
- Chrome does work OK with and without STUN servers

In the logs above, is `Components {1} have no candidate pairs` the important part that tells a negociation of some sort has failed?

I'm thinking **I** must be doing something wrong, but I'm at a loss as to what exactly… Any help, tips, pointers or anything else would be greatly appreciated.

Thanks

**Comment by RemiCardona** [comment] 2021-06-08 14:13
Some additional info, just in case:
```
test_aiortc38 ~/Projects/test_aiortc $ python --version
Python 3.8.10
```
```
test_aiortc38 ~/Projects/test_aiortc $ pip list
Package           Version
----------------- -----------
aiohttp           3.7.4.post0
aioice            0.7.5
aiortc            1.2.0
async-timeout     3.0.1
attrs             21.2.0
av                8.0.3
cffi              1.14.5
chardet           4.0.0
crc32c            2.2
cryptography      3.4.7
dnspython         2.1.0
idna              3.2
multidict         5.1.0
netifaces         0.11.0
pip               21.1.2
pycparser         2.20
pyee              8.1.0
pylibsrtp         0.6.8
setuptools        57.0.0
typing-extensions 3.10.0.0
wheel             0.36.2
yarl              1.6.3
```

**Comment by jlaine** [comment] 2021-06-30 22:06
If the behaviour is specific to Firefox, my guess would be it's due to this:

https://bugzilla.mozilla.org/show_bug.cgi?id=1691189

**Comment by jlaine** [comment] 2022-03-14 09:00
Duplicate of #481

**Closed by jlaine** 2022-03-14 09:00 UTC
Labels: duplicate
