### ISSUE TITLE
VideoStream-cli sample code

### ISSUE THREAD

**Issue by ronenc** [aiortc/aiortc#652] opened 2022-03-02 19:22 UTC
Hi,

I'm using the sample videostream-cli as is except for additional signaling server instead of copy-paste of the offer and the answer.
I'm using the options: play_from 'sample.mp4' on the offer initiate side and receive_from 'sample1.mp4' on the answer side.
All peers and signaling server are on the same PC.
Unfortunately I don't see the video received on the receiver side.
Am I missing something here?

Thanks

**Comment by jlaine** [comment] 2022-03-04 08:47
I'm completely in the dark here, you say you are using an unspecified modification to the code and it doesn't work => what do you expect from me?

Can you please report whether the example works as expected without your changes?

**Comment by ronenc** [comment] 2022-03-04 20:55
Hi Jeremy,
Thank you for your reply.
It is not quit unspecified modification.
I have an issue using the internal copy/paste provided signaling, the command signaling.connect() fails with exception, so I cannot use it.
Instead, I'm using another signaling server, and this is the only difference. I'm not sure what is the problem with that since I do get the offer/answer on both sides, which is exactly what the copy/paste signaling is trying to provide.

After the negotiation and the SDP exchanges, I do see that the "@pc.on("track")" event is triggered on both sides, but still the function "async def recv(self):" is not being called on either side.
I'm not sure if I understand if it should be called and how I can check if the video is being sent to the other peer.

Thank you for your patient

**Comment by jlaine** [comment] 2022-03-11 14:15
Duplicate of #651

**Closed by jlaine** 2022-03-11 14:15 UTC
