### ISSUE TITLE
A lightweight version of aiortc

### ISSUE THREAD

**Issue by IonesioJunior** [aiortc/aiortc#364] opened 2020-05-18 20:50 UTC
Hello! I'd like to know if it's possible to use the aiortc library without using the libav dependency.

In my use case, we're just using the data channel to exchange messages between the peers, so we probably don't need to give support for any media type. 

How difficult would it be to create a version without libav dependency?

**Comment by jlaine** [comment] 2020-05-19 06:05
Kindly check existing issues before opening new ones, this is a duplicate of #78

**Closed by jlaine** 2020-05-19 06:05 UTC
