### ISSUE TITLE
Feasibility question: webcam example with 10-15 rtsp streams

### ISSUE THREAD

**Issue by creimers** [aiortc/aiortc#354] opened 2020-05-06 09:20 UTC
I'm currently working on a web app that displays video streams from up to 15 different cameras, but at most 9 at a time.

I've been using/evaluating general purpose media servers like the [ant media server](https://antmedia.io/) until now, but for various reasons, I'm not happy with them. I am therefore considering to "roll my own" solution that is lighter and more specific.

Would you deem it feasible to accomplish the sketched scenario with aiortc? Is there anything that comes to mind to have an eye out on while attempting to implement this?

**Comment by jlaine** [comment] 2020-05-06 10:49
Sure you can implement this based on aiortc.

The main point to watch out for if you use the `webcam` example as a starting point: it's not made for broadcasting, there can only ever be one viewer at any given time. The reason is that every client that connects will result in opening the webcam, and usually they are only allowed to be open once. If you want to support broadcasting you'll need to write some kind of proxy `MediaStreamTrack` which allows multiple consumers.

**Comment by jlaine** [comment] 2021-02-12 22:02
I'm going to close this as a duplicate of #367

**Closed by jlaine** 2021-02-12 22:02 UTC
Labels: duplicate
