### ISSUE TITLE
exception raise leads to unhandled coroutine / future Task exception

### ISSUE THREAD

**Issue by julianhille** [aiortc/aiortc#948] opened 2023-10-19 11:45 UTC
There are exceptions that are raised on purpose, but not catched or bubbled up to a point
where it is or could be handled.

This leads to this log:
```
2023-10-19 ERROR (asyncio): Task exception was never retrieved
---
future: <Task finished name='Task-7510' coro=<RTCPeerConnection.__connect() done, defined at /.../venv/lib/python3.11/site-packages/aiortc/rtcpeerconnection.py:1000> exception=InvalidStateError('RTCIceTransport is closed')>
Traceback (most recent call last):
  File "/.../venv/lib/python3.11/site-packages/aiortc/rtcpeerconnection.py", line 1008, in __connect
    await iceTransport.start(self.__remoteIce[transceiver])
  File "/.../venv/lib/python3.11/site-packages/aiortc/rtcicetransport.py", line 312, in start
    raise InvalidStateError("RTCIceTransport is closed")
aiortc.exceptions.InvalidStateError: RTCIceTransport is closed
```

this exception is raised here:
https://github.com/aiortc/aiortc/blob/9f14474c0953b90139c8697a216e4c2cd8ee5504/src/aiortc/rtcicetransport.py#L304-L313

called from here:
https://github.com/aiortc/aiortc/blob/9f14474c0953b90139c8697a216e4c2cd8ee5504/src/aiortc/rtcpeerconnection.py#L1002-L1010

and this again from here:
https://github.com/aiortc/aiortc/blob/9f14474c0953b90139c8697a216e4c2cd8ee5504/src/aiortc/rtcpeerconnection.py#L987

or here:
https://github.com/aiortc/aiortc/blob/9f14474c0953b90139c8697a216e4c2cd8ee5504/src/aiortc/rtcpeerconnection.py#L800

**Comment by jlaine** [comment] 2023-12-01 00:33
Looks like a duplicate of #911

**Closed by jlaine** 2023-12-01 00:33 UTC
