### ISSUE TITLE
await pc.close() does not complete if its sending tracks were stopped() before

### ISSUE THREAD

**Issue by ibc** [aiortc/aiortc#283] opened 2020-02-21 17:21 UTC
Our Python app (which uses `aiortc`) uses the default asyncio `loop`:

```py
loop = asyncio.get_event_loop()
```

I expect this to be the same `loop` used by `aiortc` code. When we wish to finish our Python program we close all our asyncio tasks and so on, and also close all `aiortc` objects:

```py
    async def shutdown() -> None:
        # close our channel
        await channel.close()

        # close all aiortc MediaPlayers
        for player in players.values():
            if player.audio:
                player.audio.stop()
            if player.video:
                player.video.stop()

        # close all aiortc PeerConnections
        for pc in pcs.values():
            await pc.close()

        # stop the loop (just in case)
        loop.stop()
```

```py
    try:
        loop.run_until_complete(
            # our stuff here
        )
    # reached after calling channel closure
    except RuntimeError:
        pass
    finally:
        loop.run_until_complete(
            shutdown()
        )
```

The thing is, when calling `shutdown()` function, sometimes the python process does **NOT** terminate. By adding some logs we **clearly** see that, eventually, a call to `await pc.close()` **never** completes, and that's the problem.

This usually happens when the webcam is active.

**However**, if we close all the pcs **before** we close the `players`, then everything works fine. So IMHO there is a bug when closing a `MediaPlayer` whose tracks are being used by a `PeerConnection`.

This is easily reproducible. We can also just close a specific `MediaPlayer` and, if its tracks were being sent by a `PeerConnection`, then `await pc.close()` does **NOT** complete.

**Comment by ibc** [comment] 2020-02-21 17:31
It happens if I stop the `player.audio` track of a mic player and/or the `player.video` track of a webcam player (it happens if such a track was used within a PeerConnection).

**Comment by jlaine** [comment] 2020-02-21 19:23
Why are you calling stop() on the tracks at all? I don't believe in he examples do this anywhere

**Comment by ibc** [comment] 2020-02-21 19:49
Because that's how the WebRTC API works. When you close a PC the sending tracks remain Alive until you stop(), and I should be able to reuse those tracks in any other pc or even in the same pc of I did not close it before.

**Comment by ibc** [comment] 2020-02-21 20:15
This is, a track represents a source. I pass it to a pc yo encode it and send to a destination, that's all. The pc should not **own** the track nor it should **kill** it when the pc or the transceiver is closed.

I've seen this design flaw in many WebRTC implementations (including mine).

Just try in the browser. Do getUserMedia, pass the tracks to a pc and close the pc. The tracks remain alive and usable. The pc does not own the tracks but the JS application that obtained them via getUserMedia.

**Comment by jlaine** [comment] 2020-02-21 20:34
Feel free to propose a PR, I'm not understanding the issue here.

**Comment by ibc** [comment] 2020-02-21 21:02
Perhaps I wrongly anticipated a design flaw here. Ok, let me ask some questions so I'll know where the lib is supposed or not to behave as I expect. Every bullet below is 100% valid in the browser, let's see in aiortc:

1. I get a local track 1 and do pc.addTransceiver with it.
2. I call stop() on track 1. The pc should not send anything from now on (or just silence or black frames) but everything must be ok.
3. I get another new track 2 and call transceiver.sender.replaceTrack() with it. The pc should send it.
4. I close the pc. Track 2 must still be alive and usable.
5. I create a new pc 2 and call addTransceiver with track 2. It must work.
6. I create another transceiver in pc 2 with the same track 2. It must work.

Which ones of the bullets above are supposed to work in aiortc?

**Comment by jlaine** [comment] 2020-02-22 09:27
I understand the expected behaviour better now but I think this means a significant refactoring in the way tracks work. My main problem is that unlike in the browser world we are allowing users to define their own tracks, and I still don't have a clear vision of how to provide just enough API to make sure all subclasses work as expected.

**Comment by jlaine** [comment] 2020-02-22 09:31
> It happens if I stop the `player.audio` track of a mic player and/or the `player.video` track of a webcam player (it happens if such a track was used within a PeerConnection).

Does this mean that when sending media from a "cold" source (such as a video file) you don't get the hang?

There is a difference in how I handle "live" and "cold" media sources. For the first kind, MediaPlayer will throttle reading to ensure we don't buffer more than 1s of media, since these media don't have an intrinsic "clock" (we could read all the media at once). For the second kind I read and process the media as soon as they are produced.

**Comment by jmillan** [comment] 2020-02-22 11:00
@jlaine,

I've created [few tests](https://github.com/jmillan/aiortc/commit/a96015ced88acbf5ffe94e03a58616a06c11deed) demonstrating this and another related issues.

The tests use live and cold tracks. Some stop the tracks before calling `pc.close()` and some others don't.

These are the tests results which are hope help for the resolution of the issues. Let us know if we can help anyhow.

## live tracks

* test_audio_live_stoptracks: ✅ 
* test_audio_live_nostoptracks: ✅ 
* test_video_live_stoptracks: ✅ 
* test_video_live_nostoptracks: ✅ 
* test_audio_video_live_stoptracks: ❌ pc1 hangs `on pc.close()`
* test_audio_video_live_nostoptracks: ✅ 

## cold tracks

* test_audio_cold_stoptracks: ✅ 
* test_audio_cold_nostoptracks: ✅ 
* test_video_cold_stoptracks:  ✅ 
* test_video_cold_nostoptracks:  ✅ 
* test_audio_video_cold_stoptracks: ❌ segmentation fault
* test_audio_video_cold_nostoptracks: ❌ `line 101, in player_worker ValueError: stream index 1 out of range`

**Comment by jmillan** [comment] 2020-02-22 11:01
BTW, live tracks are created for MacOS only, If you use another platform feel free to modify the tests to add support for it or just let me know

**Comment by jlaine** [comment] 2020-02-23 10:10
@jmillan I think the key problem here was the crash when closing audio + video tracks, this is now fixed in master.

I've just created a PR which tests audio + video on a local video file, I'd rather not depend on the availability of an online video. In the meantime could you re-run your own tests?

I understand your wish to not have RTCRtpSender stop the tracks, but this is a distinct issue which I'd like to handle separately.

**Comment by jmillan** [comment] 2020-02-23 23:21
Sure, makes total sense.

**Comment by jlaine** [comment] 2020-02-24 09:00
Could you let me know if you still get a hang on `pc.close()` under any conditions? If not I suggest we close this issue and start a new one focused on not making RTCPeerConnection close the tracks when it closes.

**Comment by ibc** [comment] 2020-02-24 12:10
Hi @jlaine, unclear yet. I'm testing aiortc master branch and `await pc.close()` does not complete. This happens "randomly", specially if I stop the local mic/webcam tracks before calling `await pc.close()`. This is the shutdown flow when the `pc` was sending mic and video tracks:

```
worker: processNotification() [event:player.close]
--- worker.py: player.audio.stop()...
--- worker.py: player tracks stop() DONE
worker: processNotification() [event:player.stopTrack]
worker: processNotification() [event:player.close]
--- worker.py: player.video.stop()...
--- worker.py: player tracks stop() DONE
worker: processNotification() [event:handler.close]
--- handler.py: await self._pc.close()...
handler: signalingstatechange [state:closed]
```

After `await self._pc.close()` there is a `print("--- handler.py: await self._pc.close() DONE!")` log that never happens. In fact, the Python process remains zombie (its PPID is now `1`).

**Comment by ibc** [comment] 2020-02-24 12:19
Also, if I have the mic and webcam tracks being sent into the `pc` and stop the webcam track (`webcamPlayer.video.stop()`)  and seconds later I close the `pc`, the same happens: `await pc.close()` does not complete.

**Comment by jmillan** [comment] 2020-02-24 15:00
Hi, I created a PR on this regard #292

**Closed** 2020-02-24 22:40 UTC
