### ISSUE TITLE
Packet Unpack Issue with cli.py

### ISSUE THREAD

**Issue by luz-camacho** [aiortc/aiortc#770] opened 2022-09-14 00:18 UTC
Hello! 

I’m running into a unpack error when running one of the examples available in the repo, [cli.py](https://github.com/aiortc/aiortc/blob/main/examples/videostream-cli/cli.py), when I’ve upgraded some libraries. I upgraded the pyAv library from version 8.0.2 to version 9.2.0 and the aiortc library from version 1.2.1 to version 1.3.2. Now when running the cli.py example, I run into this unpack error: 

> WARNING:aiortc.rtcdtlstransport:RTCDtlsTransport(client) Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/aiortc/rtcdtlstransport.py", line 498, in __run
>     await self._recv_next()
>   File "/usr/local/lib/python3.7/dist-packages/aiortc/rtcdtlstransport.py", line 599, in _recv_next
>     await self._handle_rtp_data(data, arrival_time_ms=arrival_time_ms)
>   File "/usr/local/lib/python3.7/dist-packages/aiortc/rtcdtlstransport.py", line 542, in _handle_rtp_data
>     packet = RtpPacket.parse(data, self._rtp_header_extensions_map)
>   File "/usr/local/lib/python3.7/dist-packages/aiortc/rtp.py", line 687, in parse
>     packet.extensions = extensions_map.get(extension_profile, extension_value)
>   File "/usr/local/lib/python3.7/dist-packages/aiortc/rtp.py", line 84, in get
>     values.abs_send_time = unpack("!L", b"\00" + x_value)[0]
> struct.error: unpack requires a buffer of 4 bytes

I’ve done some more digging into this issue and this is what I’ve found. I did a lot of comparing the behavior between the two versions of these libraries as this error only occurs with the upgraded libraries. This unpack error is thrown when trying to unpack the header in a packet carrying a video frame from the client media player track, transmitting a video with audio. So, I dug more as to why the same video generates two packets with different headers across the two versions. I managed to narrow down the issue to this function in the rtp.py file, [set(self, values: HeaderExtensions)](https://github.com/aiortc/aiortc/blob/main/src/aiortc/rtp.py). 

Using the same video file as control, it seems for the new libraries end up having different extension values added to the header because the new libraries causes this condition in the set function to be triggered: 

`if values.audio_level is not None and self.__ids.audio_level:`

This value causes the extension value to look like this with the new libraries (pyAV 9.2.0, aiortc 1.3.2). This output was taking by logging the extension value parse classmethod for the RtpPacket class:

`AIORTC extension value: b'\x100 \x7f'`

With this extension value the subsequent packet is then unpacked, the above error is generated by the answer role. Meanwhile this same packet generates this different extension value in the old libraries (pyAV 8.0.2, aiortc 1.2.1):

`AIORTC extension value: b'\x101"8U=\x00\x00'`

Has anyone encountered this issue before? Error should be easy to repro by running the cli.py example using the same version of the libraries throwing the error and using any video with audio as control. In my runs I also made sure to enable logging and used the –play-from and –record-to parameters in the offer/answer roles respectively.

**Comment by AD11sbDC** [comment] 2022-09-29 09:48
Hello , I face the exact same problem as @luz-camacho when I try to receive audio and video frames from a remote python client and display the video frames in my custom made UI using PySide2. Are there any updates on this issue?

Thanks!

**Comment by luz-camacho** [comment] 2022-09-30 18:27
Reposting from the advice I gave in issue #778 

Through some more research I've found that the culprit is in the newest audio_level feature added to media packets with audio. In the the _next_encoded_frame function in the [rtcrtpsender.py](https://github.com/aiortc/aiortc/blob/main/src/aiortc/rtcrtpsender.py), we computer a new "audio_level" data point which is packed into a new class RTCEncodedFrame.

Having this audio level data point changes up what gets packed in the header extensions. I tracked down the additions to the header extensions and this new audio level feature to this commit: https://github.com/aiortc/aiortc/commit/a9a3cd9cef6ce066dbb07b690652aaff242a3773

If you want another temp fix, you can try forcing the audio_level to None in rtcrtpsender.py, which should stop the new audio level header extension from being added to the packet at all and should make everything parse correctly.

**Comment by jlaine** [comment] 2023-01-23 07:31
Hi! I'm not sure I understand the issue here, do both parties support the audio level header extension?

**Comment by jlaine** [comment] 2023-01-23 23:25
This is a duplicate of #745

**Closed by jlaine** 2023-01-23 23:25 UTC
