### ISSUE TITLE
aiortc multiple camera connection problem

### ISSUE THREAD

**Issue by SourceCodeZone** [aiortc/aiortc#398] opened 2020-07-25 09:37 UTC
I have following code  where the server peer with camera running aiortc and client peer is browser. The signaling is done through websocket. The implementation procedure is,

1. Browser client send camconnect request.
2. Server receive it and send offer to browser peer 
3. The browser receive offer and create answer and send back to server.
4. The server receive the answer and start streaming the video.  

 The code works fine only when the browser peer send only one cam-connect request. If there are two camera on server and two cam-connect request send from browser simultaneously, only the second camera playing. I can see the first cam connected but not playing(busy indicator showing).

 Also  if I send  cam-connect request one by one, that is send second cam-connect request after first camera connected then it works, both cam playing. But in this case during the second camera connection going on the first camera paused until the second camera connected. I think some problem in the coding below. Do I need to create thread for each camera connection. That is for signaling handle. 

```

async def signalingServerConnect(args):
    global signaling
    signaling = create_signaling(args)
    # connect signaling
    await signaling.connect()
    
    #consume signaling
    while True:
        obj = await signaling.receive()
        if obj["type"] == "answer":
                message = {"sdp": obj["sdp"], "type": obj["type"]}
                msgObj = RTCSessionDescription(**message)
                if isinstance(msgObj, RTCSessionDescription):
                    pc = pcs[obj["cameraName"]]
                    await pc.setRemoteDescription(msgObj)
                    print("RTCSessionDescription recived...")
                elif isinstance(msgObj, RTCIceCandidate):
                    print("Adding IceCandidate...")
                    await pc.addIceCandidate(obj)
       

        elif obj["type"] == "connect_cam_req":
            pc = RTCPeerConnection(configuration=RTCConfiguration(iceServers=[RTCIceServer( urls=['stun:stun.l.google.com:19302'])]))
            player = MediaPlayer("/dev/video0", format="v4l2", options=options) // only for demo, this will change in real case multiple camera
            if player and player.audio:
                    pc.addTrack(player.audio)
            if player and player.video:
                    pc.addTrack(player.video)

            peerName = obj["cameraName"]
            pcs[peerName] = pc



            await pc.setLocalDescription(await pc.createOffer())
            message = json.dumps({"sdp": pc.localDescription.sdp, "type": pc.localDescription.type,"cameraName": obj["cameraName"]}, sort_keys=True)
            await signalingServerSend(message)

            @pc.on('iceconnectionstatechange')
            async def on_iceconnectionstatechange():
                print('ICE connection state is----', pc.iceConnectionState)
                if pc.iceConnectionState == 'failed':
                    await pc.close()
                    pcs.discard(pc)


if __name__ == "__main__":

    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(
            signalingServerConnect(args)
        )
    #except KeyboardInterrupt:
     #   pass
    finally:
        # cleanup
        loop.run_until_complete(signaling.close())
        loop.run_until_complete(on_shutdown)
```

**Comment by jlaine** [comment] 2021-01-29 08:46
I'm not sure I understand what you mean, but : are you trying to serve a given camera to more than one user? If so it's definitely going to break down, the camera can only be opened once at a time.

**Comment by jlaine** [comment] 2021-02-12 22:03
Looks like a duplicate of #367

**Closed by jlaine** 2021-02-12 22:03 UTC
Labels: duplicate
