### ISSUE TITLE
aiortc in firefox

### ISSUE THREAD

**Issue by andrey-pr** [aiortc/aiortc#892] opened 2023-06-12 15:56 UTC
Hello.
According to documentation, aiortc doesn't work in firefox (I tested on latest version, its true). As I can see by same issues, this problem is existing for several years. As it described there, its a bug in browser, but in other project, such as https://github.com/mpromonet/webrtc-streamer webrtc in firefox works well. Unfortunatelly, other projects are not work on python.
Have you any plans to fix issue with firefox?

**Comment by farizalmustaqim** [comment] 2023-06-13 04:46
same problem

**Comment by Alpe6825** [comment] 2023-08-31 13:59
+1

**Comment by lgrahl** [comment] 2023-09-11 15:03
Can you elaborate where it states that in the docs and what does not work with Firefox?

**Comment by guidocalvano** [comment] 2023-10-14 19:28
The example for streaming to the browser does not work in firefox, see here: https://github.com/aiortc/aiortc/tree/main/examples/webcam

Apparently you need to implement trickle ice and then it works. If you do that your implementation is basically complete. But right now it is just annoyingly unable to run on firefox...

Trickle ice does not seem like it is end of the world complicated: https://www.youtube.com/watch?v=oIDYLwaalcs

**Comment by lgrahl** [comment] 2023-10-16 08:07
Duplicate of #691 then.

**Closed by lgrahl** 2023-10-16 08:07 UTC
