### ISSUE TITLE
Support `conda install aiortc`

### ISSUE THREAD

**Issue by oeway** [aiortc/aiortc#120] opened 2019-01-14 16:42 UTC
Hi, I think it would be great if `aiortc` can be installed with `conda` directly. 

The benefit of having it on conda is that it will be able to solve those dependencies with one command (`conda install aiortc`). 

Currently, on OSX, I can do `conda install ffmpeg libopus libvpx pkg-config` and then `pip install aiortc` within conda.

Potentially, it should be possible to run `conda install aiortc` on windows (https://github.com/jlaine/aiortc/issues/50).

I haven't tried, but I can find recipes for `libopus` and `libvpx` which should work with windows:

https://github.com/conda/conda-recipes/tree/master/libopus
https://github.com/conda/conda-recipes/tree/master/libvpx

**Comment by jlaine** [comment] 2019-01-14 22:09
You're welcome to submit a PR, I have no experience with using conda.

**Comment by cspark777** [comment] 2019-11-15 08:05
Hi, when I tried to install via pip, I've got issue as following:
building 'aiortc.codecs._opus' extension 
error: Microsoft Visual C++ 14.0 is required.
so I'd like to know how I can install aiortc in windows(7 or 10).
How can I install it even manually?

**Comment by systemshift** [comment] 2020-06-10 09:00
Hi, trying to get our project on conda, the issue is aiortc is a dependency and cannot be built without a full dependency tree. I can help get the package on the repo but someone has to be the package maintainer who understands the package.

So the fastest way to do it.
- fork https://github.com/conda-forge/staged-recipes
- create a branch named aiortc
- `pip install grayskull`
- `grayskull pypi aiortc`
- commit and push the `meta.yaml` file as `recipe/aiortc/meta.yaml`
- make a PR for the initial build and edit the meta file depending on the feedback review

gitter conda-forge is the place to ask for review once I PR is made

**Comment by jlaine** [comment] 2021-02-12 22:07
I'm going to close this since binary wheels are available for Linux / OS X / Windows.

**Closed by jlaine** 2021-02-12 22:07 UTC
Labels: enhancement, help wanted
