### ISSUE TITLE
AssertionError on `setRemoteDescription`

### ISSUE THREAD

**Issue by seosmeal** [aiortc/aiortc#140] opened 2019-02-01 03:44 UTC
Hi, I'm running into a problem while trying to `setRemoteDescription` for my SDP offer. I'm following something similar to the server example by using aiohttp. The SDP offer seems fine but I'm not sure if it's a codec issue or something. My handler code is shown below:
```
async def offer(request):
    # Extract SDP offer from request
    body = await request.json()
    offer = RTCSessionDescription(
        sdp=body['offer'],
        type='offer'
    )

    # Create new peer connection
    pc = RTCPeerConnection()
    pcs.add(pc)

    # Handle offer
    await pc.setRemoteDescription(offer)
    print(f'Received offer: {pc.remoteDescription}')

    # Generate answer
    await pc.setLocalDescription(await pc.createAnswer())
    print(f'Generated answer: {pc.localDescription}')

    # Send answer to server
    return web.Response(
        content_type='application/json',
        text=json.dumps({
            'response': pc.localDescription.sdp
        })
    )
```

My SDP offer is this:
```
v=0
o=- 3757974439 3757974439 IN IP4 0.0.0.0
s=a 2 z
t=0 0
a=group:BUNDLE audio0 video0
m=audio 6723 UDP/TLS/RTP/SAVPF 96 0
c=IN IP4 10.0.13.14
a=setup:actpass
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=rtpmap:96 opus/48000/2
a=rtcp:6723 IN IP4 10.0.13.14
a=rtcp-mux
a=sendrecv
a=mid:audio0
a=ssrc:93262937 cname:user2456294556@host-7187e820
a=ice-ufrag:y4GN
a=ice-pwd:67P4WMTNUN4NyZSTX3ng+M
a=fingerprint:sha-256 6D:8E:91:CF:0F:02:C9:3C:FC:DE:A7:25:9E:4B:0D:D3:B5:93:10:A7:24:1C:6C:F7:35:6A:A2:69:FF:FB:B9:07
a=candidate:1 1 UDP 2013266431 10.0.13.14 8691 typ host
a=candidate:2 1 TCP 1015021823 10.0.13.14 9 typ host tcptype active
a=candidate:3 1 TCP 1010827519 10.0.13.14 6723 typ host tcptype passive
a=candidate:1 2 UDP 2013266430 10.0.13.14 44778 typ host
a=candidate:2 2 TCP 1015021822 10.0.13.14 9 typ host tcptype active
a=candidate:3 2 TCP 1010827518 10.0.13.14 47745 typ host tcptype passive
m=video 6723 UDP/TLS/RTP/SAVPF 99
c=IN IP4 10.0.13.14
b=AS:500
a=setup:actpass
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=rtpmap:99 H264/90000
a=rtcp:6723 IN IP4 10.0.13.14
a=rtcp-mux
a=sendrecv
a=mid:video0
a=rtcp-fb:99 nack
a=rtcp-fb:99 nack pli
a=rtcp-fb:99 ccm fir
a=ssrc:3628611460 cname:user2456294556@host-7187e820
a=ice-ufrag:y4GN
a=ice-pwd:67P4WMTNUN4NyZSTX3ng+M
a=fingerprint:sha-256 6D:8E:91:CF:0F:02:C9:3C:FC:DE:A7:25:9E:4B:0D:D3:B5:93:10:A7:24:1C:6C:F7:35:6A:A2:69:FF:FB:B9:07
a=candidate:1 1 UDP 2013266431 10.0.13.14 8691 typ host
a=candidate:2 1 TCP 1015021823 10.0.13.14 9 typ host tcptype active
a=candidate:3 1 TCP 1010827519 10.0.13.14 6723 typ host tcptype passive
a=candidate:1 2 UDP 2013266430 10.0.13.14 44778 typ host
a=candidate:2 2 TCP 1015021822 10.0.13.14 9 typ host tcptype active
a=candidate:3 2 TCP 1010827518 10.0.13.14 47745 typ host tcptype passive
```

**Comment by jlaine** [comment] 2019-02-02 17:59
AFAICT the assertion being triggered is here:

https://github.com/aiortc/aiortc/blob/53e7baebefc2bb439eb303a71db2d25f81e7e7f3/aiortc/rtcpeerconnection.py#L669

This would mean no common codec could be negociated (I should throw a more helpful exception), due to how H.264 is matched : aiortc checks the parameters on the `rtpmap` and the offer you pasted has none.

Can I ask what stack produces this offer so that I can try reproducing this on my side?

**Comment by jlaine** [comment] 2019-02-04 21:03
@seosmeal ping?

**Comment by seosmeal** [comment] 2019-02-08 21:25
Sorry for the no response. I looked at a past issue where someone was using Kurento and that it worked. I'm trying to do the same thing but I see that the SDP in that issue is VP8. I guess this is a Kurento specific problem by not including the ftmp line in the SDP.

**Comment by jlaine** [comment] 2019-02-09 10:04
If you cannot help me reproduce this, I don't have any choice but to close this issue.

**Closed by jlaine** 2019-02-09 10:04 UTC
