### ISSUE TITLE
datachannel-cli/cli.py with coturn: 400 - You cannot use the same channel number with different peer

### ISSUE THREAD

**Issue by C-monC** [aiortc/aiortc#565] opened 2021-09-10 09:58 UTC
Hi,

I have a similar error to [this issue](https://github.com/aiortc/aiortc/issues/479) except there is no 403.

My modifications to cli.py:
```
    configuration = RTCConfiguration([
        RTCIceServer("turn:<coturn_ip>:3478", "test", "test"),
        # RTCIceServer("stun:stun.l.google.com:19302")
    ])
```
coturn is newest apt install (4.5.1.1-1.1ubuntu0.20.04.2) 
turnserver started with:
`turnserver -a -v -n --no-dtls --no-tls -u test:test -r realmName`

peer1:
> python cli.py offer -s copy-and-paste

peer2:
> python cli.py answer -s copy-and-paste

After pasting the dict from peer1 into peer2
```
Task exception was never retrieved
future: <Task finished coro=<TurnClientMixin.send_data() done, defined at /home/ben/Documents/gaaitjie boks/venv/lib/python3.6/site-packages/aioice/turn.py:241> exception=TransactionFailed(Message(message_method=Method.CHANNEL_BIND, message_class=Class.ERROR, transaction_id=b'\x9b\xc2n\xc2-\x00\xab\x99\xf5\xe1\xb5\xec'),)>
Traceback (most recent call last):
  File "/home/ben/Documents/gaaitjie boks/venv/lib/python3.6/site-packages/aioice/turn.py", line 251, in send_data
    await self.channel_bind(channel, addr)
  File "/home/ben/Documents/gaaitjie boks/venv/lib/python3.6/site-packages/aioice/turn.py", line 85, in channel_bind
    await self.request_with_retry(request)
  File "/home/ben/Documents/gaaitjie boks/venv/lib/python3.6/site-packages/aioice/turn.py", line 213, in request_with_retry
    response, addr = await self.request(request)
  File "/home/ben/Documents/gaaitjie boks/venv/lib/python3.6/site-packages/aioice/turn.py", line 200, in request
    return await transaction.run()
  File "/home/ben/Documents/gaaitjie boks/venv/lib/python3.6/site-packages/aioice/stun.py", line 299, in run
    return await self.__future
aioice.stun.TransactionFailed: STUN transaction failed (400 - You cannot use the same channel number with different peer)
```
output on coturn after peer offer:
```
1014: handle_udp_packet: New UDP endpoint: local addr 22.71.248.243:3478, remote addr 105.18.196.18:37119
1014: session 000000000000000003: realm <realmName> user <>: incoming packet message processed, error 401: Unauthorized
1014: IPv4. Local relay addr: 22.71.248.243:51850
1014: session 000000000000000003: new, realm=<realmName>, username=<test>, lifetime=600
1014: session 000000000000000003: realm <realmName> user <test>: incoming packet ALLOCATE processed, success

```
output on coturn after peer accept:
```
1053: handle_udp_packet: New UDP endpoint: local addr 22.71.248.243:3478, remote addr 102.14.155.24:53946
1053: session 000000000000000004: realm <realmName> user <>: incoming packet message processed, error 401: Unauthorized
1054: IPv4. Local relay addr: 22.71.248.243:52532
1054: session 000000000000000004: new, realm=<realmName>, username=<test>, lifetime=600
1054: session 000000000000000004: realm <realmName> user <test>: incoming packet ALLOCATE processed, success
1054: session 000000000000000004: realm <realmName> user <test>: incoming packet ALLOCATE processed, success
1054: session 000000000000000004: peer 10.0.0.10:33588 lifetime updated: 600
1054: session 000000000000000004: realm <realmName> user <test>: incoming packet CHANNEL_BIND processed, success
1054: session 000000000000000004: realm <realmName> user <test>: incoming packet CHANNEL_BIND processed, error 400: You cannot use the same channel number with different peer
1054: session 000000000000000004: realm <realmName> user <test>: incoming packet message processed, error 400: You cannot use the same channel number with different peer
1054: session 000000000000000004: realm <realmName> user <test>: incoming packet CHANNEL_BIND processed, error 400: You cannot use the same channel number with different peer
1054: session 000000000000000004: realm <realmName> user <test>: incoming packet message processed, error 400: You cannot use the same channel number with different peer
1054: session 000000000000000004: realm <realmName> user <test>: incoming packet CHANNEL_BIND processed, error 400: You cannot use the same channel number with different peer
1054: session 000000000000000004: realm <realmName> user <test>: incoming packet message processed, error 400: You cannot use the same channel number with different peer
1054: session 000000000000000004: realm <realmName> user <test>: incoming packet CHANNEL_BIND processed, error 400: You cannot use the same channel number with different peer
1054: session 000000000000000004: realm <realmName> user <test>: incoming packet message processed, error 400: You cannot use the same channel number with different peer
1054: session 000000000000000004: peer 172.18.0.1:52185 lifetime updated: 600
```

**Comment by jlaine** [comment] 2021-12-02 22:04
Looks like a duplicate of https://github.com/aiortc/aioice/issues/46

**Comment by jlaine** [comment] 2021-12-03 08:21
I'm going to close this a the solution lies in aioice, where I have a potential fix for the issue.

**Closed by jlaine** 2021-12-03 08:21 UTC
Labels: duplicate
