### ISSUE TITLE
ICE lite not working despite being documented

### ISSUE THREAD

**Issue by jmillan** [aiortc/aiortc#267] opened 2020-02-17 12:11 UTC
Hi, ICE lite does not work but it is documented.

Do you have any plan to support it?

**Comment by jlaine** [comment] 2020-02-17 20:18
You are right, there is no ICE lite support currently. The core of the change needs to happen in `aioice` but it's a very compact codebase so it should be feasible.

Is there a publicly accessible endpoint I can test against?

Let's use the following issue to track this: https://github.com/aiortc/aioice/issues/15

**Comment by ibc** [comment] 2020-02-18 00:09
I have some news, will comment in the referenced issue in `aioice`.

**Comment by jmillan** [comment] 2020-02-18 11:01
lets close this issue then it it's being handled in aiortc.

**Comment by jlaine** [comment] 2020-02-18 20:01
I'm re-opening this as I'd like to get to the bottom of it.

As far as I can tell there are a couple of areas which need attention:

- if aiortc receives an offer from a peer announcing a=ice-lite, what should it do?

- is our handling of the DTLS role when setup is 'actpass' correct? Unless I'm mistaken, we look at our ICE role at the *end* of the ICE establishment, which should take into account any ICE role conflict

- we currently do not honour 'active' or 'passive' setup values. I'm not sure what the WebRTC specs say about this. Does this have an impact for your usecase?

**Comment by ibc** [comment] 2020-02-18 20:42
> if aiortc receives an offer from a peer announcing a=ice-lite, what should it do?

* It should become ICE controlling (because the remote is ICE Lite and can never be controlling).
* It should NOT use aggressive ICE nomination (not allowed when the remote is ICE Lite, although ICE Lite servers are usually ready to handle it).
* It should send ICE Binding requests, wait for success responses form the remote, select the best one (probably the one for which a response was received first) and then mark it as candidate and send a Binding request with `USE_CANDIDATE` attribute.

Regarding DTLS in this case:

* The remote is SDP offerer, so `a=setup:actpass` is mandatory, so aiortc will choose its DTLS role and set it in its SDP answer.
* Which DTLS should aiosrtc choose in this case? Unclear, whichever is valid. Personally, we need to know it in advance to tell the server behave the opposite. AFAIS aiortc behaves as a DTLS server in this scenario.

> is our handling of the DTLS role when setup is 'actpass' correct? Unless I'm mistaken, we look at our **DTLS**  role at the end of the ICE establishment, which should take into account any ICE role conflict

aiortc should decide its DTLS role when it generates its SDP answer, and should not change it later no matter ICE role conflict happens after SDP O/A. So, once `pc.createAnswer()` is called, the generated SDP answer should have `a=setup:active` if aiortc decided to be DTLS client or `a=setup:passive` if aiortc decided to be DTLS server. Both are ok, just choose and we learn by inspecting the generated SDP answer :)

> we currently do not honour 'active' or 'passive' setup values. I'm not sure what the WebRTC specs say about this. Does this have an impact for your usecase?

When aiortc is the SDP answerer there is no issue since the SDP offer must have `a=setup:actpass` so aiosrtc chooses (as said before).

When aiortc is the SDP offerer, it must be `a=setup:actpass` so aiortc should honor the `a=setup` value in the remote SDP answer when `pc.setRemoteDescription(answer)` is called.

* If the remote SDP answer has `a=setup:active`, aiortc MUST become DSLT server.
* If the remote SDP answer has `a=passive`, aiortc MUST become DSLT client.

**Comment by jlaine** [comment] 2020-02-19 15:00
OK, the ICE changes in themselves seem easy enough. I've already modified `aioice` to use regular nomination if the remote party is ICE Lite, I need to push out a new release.

On the DTLS front though it looks as though I've done things very wrong, so it involves a bit more work.

**Comment by jlaine** [comment] 2020-02-19 22:57
I've figured out why I got the crazy idea that the DTLS role is derived from the resolved ICE role:

https://draft.ortc.org/#rtcdtlsrole*

`
The DLTS role is determined based on the resolved ICE role: the ICE controlled role acts as the DTLS client and the ICE controlling role acts as the DTLS server.
`

I guess this is one of those places where WebRTC and ORTC diverge. When using an RTCPeerConnection I'll switch to the proper WebRTC behaviour.

**Comment by ibc** [comment] 2020-02-19 23:01
Yes, agreed. When there is SDP stuff the ICE role is determined by who the SDP offerer is (unless the remote is ICE Lite, if so we must always be ICE controlling).

**Comment by jlaine** [comment] 2020-02-19 23:48
OK, the DTLS part of the problem should hopefully be addressed in #276. Would you mind trying it out and letting me know how it goes?

**Comment by ibc** [comment] 2020-02-19 23:54
Amazing. Will try, of course. Just a (stupid) question due to lack of Python knowledge:

How to make my Python app import `aiortc` from a custom folder? We install `aiortc` with `pip3` and I assume that the `import aiortc` lines in our py files expect the module to be in a well known path.

**Comment by jlaine** [comment] 2020-02-20 00:00
There are no stupid questions :)

If you want to install aiortc from a git checkout you can do:

`pip3 install -e /path/to/aiortc`

**Comment by ibc** [comment] 2020-02-20 00:11
:(

definitely not my confort zone:

```
ibc at ibc-macbook-pro in ~/src/mediasoup-client-aiortc/worker

$ pip3 install -e /Users/ibc/src/forks/aiortc

Obtaining file:///Users/ibc/src/forks/aiortc
Requirement already satisfied: aioice<0.7.0,>=0.6.15 in /usr/local/lib/python3.7/site-packages (from aiortc==0.9.23) (0.6.16)
Requirement already satisfied: av<8.0.0,>=7.0.0 in /usr/local/lib/python3.7/site-packages (from aiortc==0.9.23) (7.0.1)
Requirement already satisfied: cffi>=1.0.0 in /usr/local/lib/python3.7/site-packages (from aiortc==0.9.23) (1.14.0)
Requirement already satisfied: crc32c in /usr/local/lib/python3.7/site-packages (from aiortc==0.9.23) (2.0)
Requirement already satisfied: cryptography>=2.2 in /usr/local/lib/python3.7/site-packages (from aiortc==0.9.23) (2.8)
Requirement already satisfied: pyee>=6.0.0 in /usr/local/lib/python3.7/site-packages (from aiortc==0.9.23) (7.0.1)
Requirement already satisfied: pylibsrtp>=0.5.6 in /usr/local/lib/python3.7/site-packages (from aiortc==0.9.23) (0.6.4)
Requirement already satisfied: netifaces in /usr/local/lib/python3.7/site-packages (from aioice<0.7.0,>=0.6.15->aiortc==0.9.23) (0.10.9)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/site-packages (from cffi>=1.0.0->aiortc==0.9.23) (2.19)
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.7/site-packages (from cryptography>=2.2->aiortc==0.9.23) (1.14.0)
Installing collected packages: aiortc
  Found existing installation: aiortc 0.9.23
    Uninstalling aiortc-0.9.23:
      Successfully uninstalled aiortc-0.9.23
  Running setup.py develop for aiortc
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/ibc/src/forks/aiortc/setup.py'"'"'; __file__='"'"'/Users/ibc/src/forks/aiortc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/ibc/src/forks/aiortc/
    Complete output (21 lines):
    running develop
    running egg_info
    writing src/aiortc.egg-info/PKG-INFO
    writing dependency_links to src/aiortc.egg-info/dependency_links.txt
    writing requirements to src/aiortc.egg-info/requires.txt
    writing top-level names to src/aiortc.egg-info/top_level.txt
    reading manifest file 'src/aiortc.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'src/aiortc.egg-info/SOURCES.txt'
    running build_ext
    generating cffi module 'build/temp.macosx-10.14-x86_64-3.7/aiortc.codecs._vpx.c'
    already up-to-date
    generating cffi module 'build/temp.macosx-10.14-x86_64-3.7/aiortc.codecs._opus.c'
    already up-to-date
    building 'aiortc.codecs._opus' extension
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c build/temp.macosx-10.14-x86_64-3.7/aiortc.codecs._opus.c -o build/temp.macosx-10.14-x86_64-3.7/build/temp.macosx-10.14-x86_64-3.7/aiortc.codecs._opus.o
    build/temp.macosx-10.14-x86_64-3.7/aiortc.codecs._opus.c:541:10: fatal error: 'opus/opus.h' file not found
    #include <opus/opus.h>
             ^~~~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of aiortc
  Moving to /usr/local/lib/python3.7/site-packages/aiortc-0.9.23.dist-info/
   from /usr/local/lib/python3.7/site-packages/~iortc-0.9.23.dist-info
  Moving to /usr/local/lib/python3.7/site-packages/aiortc/
   from /usr/local/lib/python3.7/site-packages/~iortc
ERROR: Command errored out with exit status 1: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/ibc/src/forks/aiortc/setup.py'"'"'; __file__='"'"'/Users/ibc/src/forks/aiortc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by ibc** [comment] 2020-02-20 00:14
```
build/temp.macosx-10.14-x86_64-3.7/aiortc.codecs._opus.c:541:10: fatal error: 'opus/opus.h' file not found
    #include <opus/opus.h>
```

No idea why that happens. I have `opus` installed via `brew` and, otherwise, I should not have been able to install `pip3 install aiortc`...

**Comment by ibc** [comment] 2020-02-20 00:24
oh, got it! I entered my folder having the checkout of your fork and run `pip3 install .` into it.

Ok,. something is wrong. Out unit tests fail:

`ValueError: DTLS setup attribute must be 'active' or 'passive' for an answer`

I'll give more info in a few minutes.

**Comment by ibc** [comment] 2020-02-20 00:27
hehe, this is wrong:

```
if description.type in ["answer", "pranswer"] and media.dtls.role not in [
                "client",
                "server",
            ]:
                raise ValueError(
                    "DTLS setup attribute must be 'active' or 'passive' for an answer"
                )
```

Note that you are checking "client" and "server" instead of "active" and "passive" :)

**Comment by ibc** [comment] 2020-02-20 00:32
my fault, it's ok. Let me check this a bit more. I think that, in your fork, aiortc behaves different and now it becomes DTLS client when the remote is the SDP offerer.

**Comment by ibc** [comment] 2020-02-20 00:34
Yeah, so I've change our code to respect that behavior and things work fine.

**Comment by ibc** [comment] 2020-02-20 00:37
NOTE: Still I see that aiortc (in the fork) tries to be ICE controlled even if the remote is ICE Lite, but I assume that part os not yet done.

**Comment by ibc** [comment] 2020-02-20 00:46
ok, I've been able to also install `aioice` master branch (which is 0.6.17 with the ICE Lite fix) but still I see ICE Binding requests with ICE_CONTROLLED sent by aiortc to our ICE Lite server.

**Comment by jlaine** [comment] 2020-02-20 01:19
I haven't yet fixed how the ICE role is determined, I need to take into account whether the peer is Lite.

What should now be fixed on `master`:
- regular ICE nomination is used if the peer is ICE Lite
- the DTLS role is consistent with the SDP which is sent, regardless of what happens on the ICE layer

**Comment by ibc** [comment] 2020-02-20 01:23
Perfect, just let me know once you are ready and I'll test. Thanks!

**Comment by jlaine** [comment] 2020-02-20 13:18
@ibc hopefully all the issues should now be fixed on `master`, could you give it a spin?

**Comment by ibc** [comment] 2020-02-20 13:21
I must test "master" branch of both aiortc and aioice, right?

**Comment by ibc** [comment] 2020-02-20 13:38
Confirmed that everything works as expected (ICE and DTLS roles and message exchange).

May you please notify here when a new `aiortc` (and `aioice`) is released so we can also release a new version of our library? We need to make some changes when that happen related to the DTLS role.

**Comment by jlaine** [comment] 2020-02-20 14:54
`aioice` is already released (version 0.6.17) and I think I'll cut an aiortc release (0.9.24) as soon as I feed the changelog.

**Comment by jlaine** [comment] 2020-02-20 15:56
aiortc 0.9.24 is out!

**Closed by jlaine** 2020-02-20 15:56 UTC

**Comment by ibc** [comment] 2020-02-20 17:16
Tested! Big thanks!
